name = "pouetpouet"
description = "PouetPouet firmware"
version = "0.1.0-dev"

authors = ["Marc Poulhiès"]
maintainers = ["Marc Poulhiès <dkm@kataplop.net>"]
maintainers-logins = ["dkm"]

executables = ["pouetpouet"]

[configuration.values]
atomic.backend = "armv6m"
cortex_m.core = "m0"

[[depends-on]]
click = "~0.1.0-dev"
usb_embedded = "~0.3.0-dev"
gnat_arm_elf = "^12"
stm32f0x2_hal = "~0.0.0"

[build-profiles]
## Do not build stm32f0x2_hal in release mode, doesn't work (woopsy)
stm32f0x2_hal  = "development"
##click = "development"

[[pins]]
click = { url='https://github.com/dkm/click' }
usb_embedded = { url='https://github.com/dkm/usb_embedded' }
stm32f0x2_hal = { url='https://github.com/dkm/stm32f0x2_hal-ada.git' }