[package]
name = "pouetpouet"
version = "0.1.0"
authors = ["Marc Poulhiès <dkm@kataplop.net>", "Guillaume Pinot <texitoi@texitoi.eu>"]
edition = "2018"

[dependencies]
stm32f0xx-hal = { git = "https://github.com/dkm/stm32f0xx-hal/", features = ["rt", "stm32f072", "stm32-usbd"] }
##stm32f0xx-hal = { version = "0.17.0", features = ["rt", "stm32f072", "stm32-usbd"] }
cortex-m = "0.7"
cortex-m-rt = { version = "0.7", features = ["device"] }
panic-halt = "0.2"
keyberon = { git = "https://github.com/TeXiToi/keyberon" }
cortex-m-rtic = { version = "0.5", default-features = false, features = ["cortex-m-7"] }
embedded-hal = "0.2"
usb-device = "0.2"
nb = "1.0"
ws2812-spi = "0.4"
smart-leds = "0.3"

[profile.release]
lto = true
incremental = false
opt-level = "z"
debug = true

[features]
default = [ ]
testmode = [  ]
